### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by abdulrauf11** [Brand-Boosting-GmbH/hydrogen-2-vercel-demo#1]
I get this error when I run `shopify hydrogen preview`. It does complete the `build` as well. So, the error is occurring on run time.

This is what is shown on the browser:
```
FetchError [ERR_NO_HANDLER]: No fetch handler defined and no upstream to proxy to specified.
Make sure you're exporting a default object containing a `fetch` function property.
    at EventTarget.[kDispatchFetch] (/hydrogen-2-vercel-demo/node_modules/@miniflare/core/src/standards/event.ts:431:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm not sure what is going wrong here. It works perfectly fine when you run it on `dev` though.

**Comment by MurmeltierS** [comment]
`shopify hydrogen preview` expects a Oxygen Edge Function as output, but this project is configured to be deployed on Vercel for production, so this behavior is excepted.
